quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=satria123
quarkus.datasource.jdbc.url=jdbc:postgresql://192.168.100.145:5432/testdb

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true